# Generated by Django 4.1.1 on 2022-09-17 04:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Disponibilidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disp_fechad', models.DateField()),
                ('disp_precio', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='tipo_baño',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tiba_cuantos', models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='tipo_formapago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tifo_forma', models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='tipo_habitacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tiha_cuantas', models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='tipo_husped',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tihu_cuantos', models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='tipo_pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipa_pago', models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serv_internet', models.CharField(max_length=2)),
                ('serv_cocina', models.CharField(max_length=3)),
                ('serv_patio', models.CharField(max_length=3)),
                ('serv_ubicacion', models.CharField(max_length=30)),
                ('baño', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='servicios.tipo_baño')),
                ('habitacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='servicios.tipo_habitacion')),
                ('huesped', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='servicios.tipo_husped')),
            ],
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pago_fechae', models.DateField()),
                ('pago_fechas', models.DateField()),
                ('pago_valor', models.BigIntegerField()),
                ('formapago', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='servicios.tipo_formapago')),
                ('servicio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='servicios.servicio')),
                ('tipopago', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='servicios.tipo_pago')),
            ],
        ),
    ]
