# Generated by Django 4.1.1 on 2022-10-01 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0002_servicio_disponibilidad'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='disponibilidad',
            name='disp_fechad',
        ),
        migrations.AddField(
            model_name='disponibilidad',
            name='disp_disponible',
            field=models.CharField(default=1, max_length=2),
            preserve_default=False,
        ),
    ]
