# Generated by Django 4.1.1 on 2022-10-01 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0003_remove_disponibilidad_disp_fechad_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipo_formapago',
            name='tifo_forma',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='tipo_pago',
            name='tipa_pago',
            field=models.CharField(max_length=20),
        ),
    ]
