# Generated by Django 4.1.1 on 2022-10-11 02:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0004_tablamaestra_alter_cliente_oficio_and_more'),
        ('servicios', '0005_pago_realizado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pago',
            name='formapago',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='formapago', to='personas.tablamaestra'),
        ),
        migrations.AlterField(
            model_name='pago',
            name='tipopago',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tipopago', to='personas.tablamaestra'),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='baño',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='baño', to='personas.tablamaestra'),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='habitacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='habitacion', to='personas.tablamaestra'),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='huesped',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='huesped', to='personas.tablamaestra'),
        ),
        migrations.DeleteModel(
            name='tipo_baño',
        ),
        migrations.DeleteModel(
            name='tipo_formapago',
        ),
        migrations.DeleteModel(
            name='tipo_habitacion',
        ),
        migrations.DeleteModel(
            name='tipo_husped',
        ),
        migrations.DeleteModel(
            name='tipo_pago',
        ),
    ]
