# Generated by Django 4.1.1 on 2022-09-17 04:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clie_nacionalidad', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Personas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pers_nombre', models.CharField(max_length=30)),
                ('pers_apellido', models.CharField(max_length=20)),
                ('pers_identidad', models.CharField(max_length=15)),
                ('pers_telefono', models.CharField(max_length=10)),
                ('pers_direccion', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Propietario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prop_respuesta', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='tipo_identificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tiid_tipodocumento', models.CharField(max_length=30)),
                ('tiid_numerodocumento', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='tipo_oficio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tiof_oficio', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='propietariocliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='personas.cliente')),
                ('propietario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='personas.propietario')),
            ],
        ),
        migrations.AddField(
            model_name='propietario',
            name='cliente',
            field=models.ManyToManyField(through='personas.propietariocliente', to='personas.cliente'),
        ),
        migrations.AddField(
            model_name='propietario',
            name='persona',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='personas.personas'),
        ),
        migrations.AddField(
            model_name='personas',
            name='identificacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='personas.tipo_identificacion'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='oficio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='personas.tipo_oficio'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='persona',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='personas.personas'),
        ),
    ]
