# Generated by Django 4.1.1 on 2022-10-01 01:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personas',
            name='pers_identidad',
        ),
    ]
