# Generated by Django 4.1.1 on 2022-10-11 02:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0003_propietariocliente_procl_nota'),
    ]

    operations = [
        migrations.CreateModel(
            name='TablaMaestra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tama_nombre1', models.CharField(max_length=30)),
                ('tama_nombre2', models.CharField(max_length=30)),
                ('tama_dependencia1', models.CharField(max_length=30)),
                ('tama_dependencia2', models.CharField(max_length=30)),
                ('tama_codigo', models.CharField(max_length=30)),
                ('tama_estado', models.CharField(max_length=30)),
            ],
        ),
        migrations.AlterField(
            model_name='cliente',
            name='oficio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='personas.tablamaestra'),
        ),
        migrations.AlterField(
            model_name='personas',
            name='identificacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='personas.tablamaestra'),
        ),
        migrations.DeleteModel(
            name='tipo_identificacion',
        ),
        migrations.DeleteModel(
            name='tipo_oficio',
        ),
    ]
