# Generated by Django 4.1.1 on 2022-10-14 00:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0004_tablamaestra_alter_cliente_oficio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='personas',
            name='pers_numidentidad',
            field=models.CharField(default=1, max_length=45),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='propietario',
            name='persona',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Nombre', to='personas.personas'),
        ),
    ]
